services:
  - type: web
    name: drf-api
    env: python
    buildCommand: ./build.sh
    startCommand: uv run gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drf-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: drf-db
