# Generated by Django 5.2.7 on 2025-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_unhashed_password_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unhashed_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
